### ISSUE TITLE
Log file missing

### ISSUE THREAD

**Issue by snomos** [divvun/macdivvun-service#12]
When starting the MacDivvun service from the command line, it errors on the log file as follows:

```sh
/Library/Services/MacDivvun.service/Contents/MacOS/MacDivvun   
2023-04-21 13:14:34.852 MacDivvun[4598:3823691] [Error] > Attempt to open log file for writing failed: The file “MacDivvun.log” doesn’t exist.
```

Cf divvun/divvun-manager-macos/issues/37

**Comment by SteffenErn** [comment]
This was resolved by https://github.com/divvun/macdivvun-service/pull/14

**Comment by dylanhand** [comment]
@snomos can you close this if you agree it is fixed?

**Comment by snomos** [comment]
@dylanhand yes I will. Haven't had time to test it yet, will do ASAP.

**Comment by snomos** [comment]
Seems to work properly now. Closed.
