### ISSUE TITLE
Divvun installer (DI) does not install MacDivvun.service

### ISSUE THREAD

**Issue by Trondtr** [divvun/macdivvun-service#13]
I have for some time been without the catalogue `MacDivvun.service` in the */Library/Services* catalogue, hence the divvun spellers also have not been working. I have probably removed it by an attempt at a fresh start (`rm -rf /Library/Services/*`), but I do not remember. The catalogue is in any case not there. Today I removed all `*.bundle` folders, deinstalled and then reinstalled DI (=Divvun Manager). DI installed *MacInfo.workflow*. Then I installed a set of languages. The content of */Library/Services/* is now:

```
MacInfo.workflow
fit.bundle
fkv.bundle
fo.bundle
rmn.bundle
rmu.bundle
se.bundle
sma.bundle
smn.bundle
vep.bundle
```

The problem is that despite my reinstalling of DI the installation process did **not** result in a reinstalling of *MacDivvun.service*. I am thus without a working Divvun spellchecker. This may perhaps (?!) be fixed by someone sending me a copy of the folder, but what is worrying is that deinstalling DI (With CleanMyMac) and then reinstalling it does not get me back on square one.

**Comment by Trondtr** [comment]
[divvun-manager-debug.zip](https://github.com/divvun/macdivvun-service/files/11298206/divvun-manager-debug.zip)

Here is the divvun-mangager-debug file offered by **DI**.

**Comment by snomos** [comment]
`MacInfo.workflow` is not related to any Divvun component, it is installed by UiT IT management components.

**Comment by snomos** [comment]
The core of the issue:

- if a speller component is missing (the system speller component in this case), make sure it is (re)installed

**Comment by SteffenErn** [comment]
This should be solved by https://github.com/divvun/pahkat/pull/49

**Comment by snomos** [comment]
Fixed by adding description of manual cleanup in the https://github.com/divvun/divvun-manager-macos README.
